// Cookie Management â€” format converters, PostgreSQL storage, vault mirroring, node sync

import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';
import type { SyncDB } from './db.js';
import type { NodeManager } from '../nodes/manager.js';
import type { TransferEngine } from '../nodes/transfer.js';

// â”€â”€â”€ Types â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

export type CookieFormat = 'json' | 'header' | 'netscape';

export interface Cookie {
  domain: string;
  name: string;
  value: string;
  path: string;
  expires?: number;       // Unix timestamp; undefined = session cookie
  httpOnly: boolean;
  secure: boolean;
  sameSite?: 'Strict' | 'Lax' | 'None';
}

export interface CookieJar {
  domain: string;
  cookies: Cookie[];
  updatedAt: string;      // ISO 8601
  source?: string;
}

// â”€â”€â”€ Format Converters â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

export function cookiesToJson(cookies: Cookie[]): string {
  return JSON.stringify(cookies, null, 2);
}

export function cookiesToHeader(cookies: Cookie[]): string {
  return cookies.map((c) => `${c.name}=${c.value}`).join('; ');
}

/**
 * Netscape cookie file format (curl / wget compatible):
 * domain  includeSubdomains  path  secure  expiry  name  value
 */
export function cookiesToNetscape(cookies: Cookie[]): string {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by OmniWire CookieManager',
    '',
  ];

  for (const c of cookies) {
    const domain = c.domain.startsWith('.') ? c.domain : `.${c.domain}`;
    const includeSubdomains = 'TRUE';
    const path = c.path || '/';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const expiry = c.expires ?? 0;
    lines.push(
      `${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expiry}\t${c.name}\t${c.value}`,
    );
  }

  return lines.join('\n');
}

// â”€â”€â”€ Parsers â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

export function parseCookiesFromJson(raw: string): Cookie[] {
  const parsed: unknown = JSON.parse(raw);
  if (!Array.isArray(parsed)) {
    throw new Error('Expected JSON array of cookies');
  }
  return parsed as Cookie[];
}

export function parseCookiesFromHeader(header: string, domain: string): Cookie[] {
  const cleaned = header.replace(/^Cookie:\s*/i, '').trim();
  if (!cleaned) return [];

  return cleaned
    .split(';')
    .map((pair) => {
      const eqIdx = pair.indexOf('=');
      const name = eqIdx === -1 ? pair.trim() : pair.slice(0, eqIdx).trim();
      const value = eqIdx === -1 ? '' : pair.slice(eqIdx + 1).trim();
      const cookie: Cookie = {
        domain,
        name,
        value,
        path: '/',
        httpOnly: false,
        secure: false,
      };
      return cookie;
    })
    .filter((c) => c.name.length > 0);
}

export function parseCookiesFromNetscape(content: string): Cookie[] {
  const cookies: Cookie[] = [];

  for (const raw of content.split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;

    const parts = line.split('\t');
    if (parts.length < 7) continue;

    const [domainRaw, , path, secureStr, expiryStr, name, value] = parts;
    const domain = domainRaw.startsWith('.') ? domainRaw.slice(1) : domainRaw;
    const expiry = parseInt(expiryStr, 10);

    cookies.push({
      domain,
      name,
      value,
      path: path || '/',
      expires: expiry > 0 ? expiry : undefined,
      httpOnly: false,
      secure: secureStr === 'TRUE',
    });
  }

  return cookies;
}

export function parseCookies(raw: string, format: CookieFormat, domain?: string): Cookie[] {
  switch (format) {
    case 'json':
      return parseCookiesFromJson(raw);
    case 'header':
      return parseCookiesFromHeader(raw, domain ?? '');
    case 'netscape':
      return parseCookiesFromNetscape(raw);
  }
}

export function exportCookies(cookies: Cookie[], format: CookieFormat): string {
  switch (format) {
    case 'json':
      return cookiesToJson(cookies);
    case 'header':
      return cookiesToHeader(cookies);
    case 'netscape':
      return cookiesToNetscape(cookies);
  }
}

// â”€â”€â”€ Vault Mirroring â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

export function mirrorToVault(domain: string, cookies: Cookie[]): void {
  const vaultDir = join(
    homedir(),
    'Documents',
    'BuisnessProjects',
    'CyberBase',
    'credentials',
    'cookies',
  );

  if (!existsSync(vaultDir)) {
    mkdirSync(vaultDir, { recursive: true });
  }

  const now = new Date().toISOString();

  const tableRows = cookies
    .map((c) => {
      const expires = c.expires
        ? new Date(c.expires * 1000).toISOString().slice(0, 10)
        : 'session';
      const flags = [
        c.httpOnly ? 'HttpOnly' : '',
        c.secure ? 'Secure' : '',
        c.sameSite ? `SameSite=${c.sameSite}` : '',
      ]
        .filter(Boolean)
        .join(', ');
      const truncatedValue =
        c.value.length > 40 ? `${c.value.slice(0, 40)}â€¦` : c.value;
      return `| ${c.name} | ${truncatedValue} | ${c.path} | ${expires} | ${flags} |`;
    })
    .join('\n');

  const content = `---
domain: ${domain}
type: cookie
tags:
  - credentials
  - cookie
last-updated: ${now}
cookie-count: ${cookies.length}
---

# Cookies â€” ${domain}

| Name | Value | Path | Expires | Flags |
|------|-------|------|---------|-------|
${tableRows}
`;

  writeFileSync(join(vaultDir, `${domain}.md`), content, 'utf8');
}

// â”€â”€â”€ CookieManager â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

export class CookieManager {
  private readonly db: SyncDB;
  private readonly manager?: NodeManager;
  private readonly transfer?: TransferEngine;

  constructor(db: SyncDB, manager?: NodeManager, transfer?: TransferEngine) {
    this.db = db;
    this.manager = manager;
    this.transfer = transfer;
  }

  private dbKey(domain: string): string {
    return `cookie:${domain}`;
  }

  async set(domain: string, cookies: Cookie[], source?: string): Promise<void> {
    const jar: CookieJar = {
      domain,
      cookies,
      updatedAt: new Date().toISOString(),
      source,
    };

    await this.db.upsertKnowledge('omniwire', this.dbKey(domain), jar as unknown as Record<string, unknown>);
    mirrorToVault(domain, cookies);
  }

  async get(domain: string, format: CookieFormat = 'json'): Promise<string | null> {
    const entries = await this.db.getKnowledgeByPrefix('omniwire', this.dbKey(domain));
    const entry = entries.find((e) => e.key === this.dbKey(domain));
    if (!entry) return null;

    const jar = entry.value as unknown as CookieJar;
    if (!jar.cookies || jar.cookies.length === 0) return null;

    return exportCookies(jar.cookies, format);
  }

  async list(): Promise<Array<{ domain: string; count: number; updatedAt: string; source?: string }>> {
    const entries = await this.db.getKnowledgeByPrefix('omniwire', 'cookie:');

    return entries.map((e) => {
      const jar = e.value as unknown as CookieJar;
      return {
        domain: jar.domain,
        count: jar.cookies?.length ?? 0,
        updatedAt: jar.updatedAt,
        source: jar.source,
      };
    });
  }

  async delete(domain: string): Promise<void> {
    const jar: CookieJar = {
      domain,
      cookies: [],
      updatedAt: new Date().toISOString(),
    };
    await this.db.upsertKnowledge('omniwire', this.dbKey(domain), jar as unknown as Record<string, unknown> as unknown as Record<string, unknown>);
  }

  async import(
    raw: string,
    format: CookieFormat,
    domain?: string,
    source?: string,
  ): Promise<Record<string, number>> {
    const cookies = parseCookies(raw, format, domain);

    // Group cookies by their embedded domain field
    const grouped = new Map<string, Cookie[]>();
    for (const cookie of cookies) {
      const key = cookie.domain || domain || 'unknown';
      const existing = grouped.get(key) ?? [];
      grouped.set(key, [...existing, cookie]);
    }

    // If the caller provided a fallback domain and all cookies lacked one, bucket under it
    if (grouped.size === 0 && domain) {
      grouped.set(domain, []);
    }

    const results: Record<string, number> = {};
    for (const [dom, domCookies] of grouped) {
      await this.set(dom, domCookies, source);
      results[dom] = domCookies.length;
    }

    return results;
  }

  async syncToNodes(
    domain: string,
    nodeIds?: string[],
  ): Promise<Record<string, boolean>> {
    if (!this.manager || !this.transfer) {
      throw new Error('Node manager and transfer engine are required for node sync');
    }

    const entries = await this.db.getKnowledgeByPrefix('omniwire', this.dbKey(domain));
    const entry = entries.find((e) => e.key === this.dbKey(domain));
    if (!entry) {
      throw new Error(`No cookie jar found for domain: ${domain}`);
    }

    const jar = entry.value as unknown as CookieJar;
    const netscape = cookiesToNetscape(jar.cookies);
    const remotePath = `/root/.omniwire/cookies/${domain}.txt`;

    const targets = nodeIds ?? this.manager.getOnlineNodes();
    const results: Record<string, boolean> = {};

    await Promise.allSettled(
      targets.map(async (nodeId) => {
        try {
          await this.transfer!.writeFile(nodeId, remotePath, netscape);
          results[nodeId] = true;
        } catch {
          results[nodeId] = false;
        }
      }),
    );

    return results;
  }

  async syncAllToNodes(
    nodeIds?: string[],
  ): Promise<Record<string, Record<string, boolean>>> {
    const allJars = await this.list();
    const results: Record<string, Record<string, boolean>> = {};

    for (const { domain } of allJars) {
      try {
        results[domain] = await this.syncToNodes(domain, nodeIds);
      } catch {
        results[domain] = {};
      }
    }

    return results;
  }
}
